Add cluster check

diff --git a/demitas-exec b/demitas-exec
--- a/demitas-exec
+++ b/demitas-exec
@@ -65,6 +65,11 @@ if [ -n "$PROFILE" ]; then
   DEMITAS_OPTS="$DEMITAS_OPTS -p $PROFILE"
 fi
 
+if [ -n "$(aws ecs describe-clusters --cluster $CLUSTER --output text --query 'failures')" ]; then
+  echo "error: Cluster not found: $CLUSTER"
+  exit 1
+fi
+
 ECSPRESSO_POTS='--wait-until=running'
 
 echo 'Start ECS task...'
